package org.johnstonscode.samples.jaxb;

import java.util.List;

import javax.xml.bind.ValidationEvent;
import javax.xml.bind.ValidationEventHandler;

/**
 * This class implements the JAX-B {@link ValidationEventHandler} that
 * will attempt to deliver all the validation errors generated by the
 * parser. We simply record them all in a list for the client to 
 * process.
 *
 */
class ValidationEventHandlerImpl implements ValidationEventHandler {

    private final List<ValidationError> events;
    
    public ValidationEventHandlerImpl(final List<ValidationError> events) {
        this.events = events;
    }

    @Override
    public boolean handleEvent(final ValidationEvent event) {
        this.events.add(new ValidationErrorImpl(event));
        /*
         * Must return true here which asks JAX-B nicely to continue
         * processing errors if possible.
         */
        return true;
    }
}